### ISSUE TITLE
impossible to login after change

### ISSUE THREAD

**Issue by circlesymbol** [SlickDomique/open-handles#3]
hi! umm after applying the new handle, its now physically impossible to login after because  it cant contact to the service ig
![IMG_8116](https://github.com/user-attachments/assets/fdfc053d-25b9-4d7d-9915-ca26062c37ee)

**Comment by slickdomi** [comment]
@circlesymbol don't change the service, you still need to use the default bluesky one. The handle is resolved and.. handled by it.

**Comment by circlesymbol** [comment]
ok thx
